KioskTitle          string `json:"kioskTitle"`
	KioskDescription    string `json:"kioskDescription"`
	KioskLogoUrl        string `json:"kioskLogoUrl"`
	KioskBackgroundUrl  string `json:"kioskBackgroundUrl"`
	KioskBackgroundBlur int    `json:"kioskBackgroundBlur"`
	KioskBackgroundSize string `json:"kioskBackgroundSize"`
	KioskBackgroundPosX string `json:"kioskBackgroundPosX"`
	KioskBackgroundPosY string `json:"kioskBackgroundPosY"`
	KioskLogoSize       string `json:"kioskLogoSize"`
	KioskLogoPosX       string `json:"kioskLogoPosX"`
	KioskLogoPosY       string `json:"kioskLogoPosY"`
